name: front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.1.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  geolocator: ^14.0.2
  provider: ^6.1.2
  http: ^1.5.0
  sensors_plus: ^3.0.0
  google_maps_flutter: ^2.6.0
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.1.0

  firebase_core: ^3.6.0
  firebase_analytics: ^11.2.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  firebase_auth: ^5.7.0
  google_sign_in: ^7.2.0

  gap: ^3.0.1
  dropdown_button2: ^2.3.9
  camera: ^0.11.3
  audio_waveforms: ^2.0.0
  audioplayers: ^5.2.1
  avatar_glow: ^3.0.1
  flutter_tts: ^3.6.3
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: images/refeeqlogo.jpeg
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: images/refeeqlogo.jpeg
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/logologo.png
    - images/googleImage.webp
    - images/OIP.webp
    - images/profilepatient.jpg
    - images/profileimg.png
    - images/images.png
    - images/refeeqlogo.jpeg
    - images/google.png
    - images/googlelogo.png
    - images/deafpic.webp
    - images/blind.png
    - images/sign_language.png
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-VariableFont_wght.ttf
